### PR TITLE
task/WG-206: Add layout to map project page

### PR DESCRIPTION
**Pull request by nathanfranklin**
## Overview: ##

Add layout for map project page

The active panel is controlled by a query param.  

I added two "empty" panels to illustrate things and as starting point:
* AssetsPanel which opens the left side panel where the assets listing will go.
* ManageMapProjectModal which opens as a modal

## Related Jira tickets: ##

* [WG-206](https://tacc-main.atlassian.net/browse/WG-206)

## Testing Steps: ##
1. Go to http://localhost:4200/project/84592574-9be5-40cd-8664-1d42c315ef17/ and see if things work
2. Click on Assets to see left sid epanel
3. Click on Manage too see modal

## UI Photos:

Screenshot 2024-02-15 at 10 10 44 AM
Screenshot 2024-02-15 at 10 10 37 AM

### CODE REVIEW

**Review by tjgrafft — COMMENTED** [review]
I'm getting a 404 error in the console related to a GET request for index.css. The GET request URL is http://localhost:4200/project/84592574-9be5-40cd-8664-1d42c315ef17/src/index.css. 

It should be http://localhost:4200/src/index.css instead.

**Comment by tjgrafft** [comment]
I tested locally and everything (besides the 404 index.css error) looks good. You have some console.log statements that need to be taken out in various files before merging to master. Files where they appear are: MapProject, ManageMapProjectModal, installHook, and AssetsPanel.

**Review by shayanaijaz — APPROVED** [review]
LGTM. No other comments other than what Taylor has mentioned

**Comment by nathanfranklin** [comment]
> I'm getting a 404 error in the console related to a GET request for index.css. The GET request URL is http://localhost:4200/project/84592574-9be5-40cd-8664-1d42c315ef17/src/index.css.
> 
> It should be http://localhost:4200/src/index.css instead.

this is on the main branch as well and is probably https://tacc-main.atlassian.net/browse/WG-224.  adding a note there related to this.

**Comment by nathanfranklin** [comment]
@tjgrafft , this is ready for one more review. I dropped the console.logs and left a comment regarding the index.css.

**Review by tjgrafft — APPROVED** [review]
LGTM! Comments addressed

**Pull request merged**
