### PR TITLE
Task/wg 193 add tup core components lib

### PR DESCRIPTION
**Pull request by sophia-massie**
## PR Status: ##

* [X] Ready.
* [ ] Work in Progress.
* [ ] Hold.

## Related Jira tickets: ##

* [WG-193](https://tacc-main.atlassian.net/browse/WG-193)

## Summary of Changes: ##
- Added core-component dir from TUP-UI 
-  Updated configs and packages needed for core-Components
- Ignoring core-components tests in test script
- Allow for implict any type as per the tsconfigs of TUP
- Allow for js to be compiled
- Added styles README from TUP for our reference

## Testing Steps: ##
1.  Make sure you're using latest iron node by running nvm use lts/iron
2. Then npm ci
3. Then build and run dev
4. Go to http://localhost:4200/ and make sure it displays 
"Main Menu
Projects
You have {x} projects."
6. In the code base, go to src/pages/MainMenu.tsx change line 12 to (!isLoading) and make sure loading spinner appears. 
7.  In the code base, go to src/pages/MainMenu.tsx change line 19 to (!error) to make sure message displays in red.

### CODE REVIEW

**Comment by tjgrafft** [comment]
Just a heads up, the screenshots for comparison aren't rendering for me. I think the links are broken?

**Comment by sophia-massie** [comment]
> Just a heads up, the screenshots for comparison aren't rendering for me. I think the links are broken?

Try refreshing - I took those instructions/screen shots out.

**Review by tjgrafft — APPROVED** [review]
I tested everything locally and the Loading Spinner and Error Message appeared as expected! Great job! Having these common components to work with is gonna make life so much easier for us! So thanks for moving them over!

Wanted to get you and Nathan's thoughts on the following: 

- When doing the 'npm ci' command I got an output response of 8 vulnerabilities (6 moderate, 1 high, and 1 critical) Is this something in our control, that we can address?
- When doing the 'npm run build' command I got an output response of several warning related to minifying the css. Should we make a sub-task to handle this later?

**Review by nathanfranklin — APPROVED** [review]
Awesome. LGTM 👍

**Pull request merged**
